name: CI
on: push

jobs:
  test-flamegraph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - run: cargo install flamegraph
    - run: sudo flamegraph ls
